GH196: Fix terminateJob
haskell/process pull request #199
Opened 2020-12-18 17:54 UTC by Mistuke

Hi,

`terminateJob` is being called from within `terminateProcess` which already has a lock on the `MVar`. 
This add a new function `terminateJobUnsafe` which does not take an `MVar` and so is not thread-safe but can be called from `terminateProcess` safely.

Fixes #196

2020-12-20 06:21 UTC, snoyberg commented
The AppVeyor tests failed on this build.

Side note: I think I'll move CI over to Github Actions instead of the Travis/AppVeyor split, just an FYI.

2020-12-29 10:37 UTC, Mistuke commented
> The AppVeyor tests failed on this build.
> 

That test is somewhat broken which is why it sometimes passes and sometimes fails. See https://sourceforge.net/p/mingw/mailman/mingw-users/thread/CAO2ddnbqqTwABiLSpyDN-ynyQR%3D6fRt5Mt94gszkgQoJF-atOA%40mail.gmail.com/#msg30566147

In general there's no guarantee that the PID inside a Cygwin process is the same as the PID in Windows. Cygwin is trying to emulate a posix environment in user space.  It will try to have the PIDs match but this may not always succeed which is why this test is flaky.

In any case, I've updated the test to read the `winpid` from `procfs` instead.

2021-01-03 15:21 UTC, Mistuke commented
@snoyberg alright, the test is fixed to work properly on Windows now.

2021-01-03 15:23 UTC, snoyberg requested changes
Looks great. One more request: could you add a changelog entry explaining the change?

2021-01-03 15:26 UTC, Mistuke commented
Done.

2021-01-03 15:27 UTC, snoyberg approved these changes

2021-01-03 15:27 UTC, merged

2021-01-03 15:27 UTC, snoyberg commented
Thanks!